# Generated by Django 5.2 on 2025-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='successfull', max_length=50),
        ),
    ]
